global using static System.Net.Mime.MediaTypeNames;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using System.ComponentModel.DataAnnotations;
global using GameZone.Models;
global using GameZone.Services;
global using GameZone.ViewModels;
global using GameZone.Data;
global using GameZone.Settings;
